export const siteConfig = {
  name: "Arjun Shenoy R",
  role: "AI/ML Enthusiast · Software Engineering · Research",
  tagline: "Building software, exploring AI, and turning ideas into working systems.",
  title: "Arjun Shenoy R — AI/ML Enthusiast & Software Developer",
  description:
    "Arjun Shenoy R is a Computer Science Engineering student interested in machine learning, software engineering and research. Projects, research work and hackathon builds.",
  url: "https://arjun-shenoy-portfolio.vercel.app",
  github: "https://github.com/Arjun13-git",
  githubHandle: "Arjun13-git",
  linkedin: "https://linkedin.com/in/arjun-shenoy-r",
  email: "ranjalarjunshenoy@gmail.com",
  resumeUrl: "/resume/resume.pdf",
  location: "Mangalore, Karnataka, India",
  college: "Sahyadri College of Engineering & Management",
  degree: "B.E. Computer Science & Engineering",
  cgpa: "8.67",
  keywords: [
    "Arjun Shenoy R",
    "AI/ML Enthusiast",
    "Machine Learning",
    "Software Engineering",
    "Computer Science student",
    "Research",
    "Quantum Machine Learning",
    "Python",
    "FastAPI",
    "Next.js",
    "Portfolio",
  ],
} as const;
